### ISSUE TITLE
Update Sonar Scanner to 3.2.0

### ISSUE THREAD

**Issue by rogervila** [mercuriete/docker-sonar-scanner#1]

**Comment by mercuriete** [comment]
Lol
I didn't read this issue

@rogervila this project is a spare time project so I will work on this project on "best effort".

Thanks for your interest

PD: niiiñooooo fuerte puta mierda xD

**Comment by mercuriete** [comment]
hi @rogervila 
the latest version of sonar scanner is:

3.2.0.1227

https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/

So I am targeting to move to that version.

Thanks for your interest.

**Comment by mercuriete** [comment]
hi @rogervila 
this request was done in commit: https://github.com/mercuriete/docker-sonar-scanner/commit/b8826db7fb5e73bfca7cc99e7058fb4e44e67466

Please reopen if you found any bug.
